# Generated by Django 5.2 on 2025-05-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stories", "0002_story_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="indicator",
            field=models.CharField(default="Indicator1", max_length=255),
            preserve_default=False,
        ),
    ]
